// 'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from '@/_components/nav/NavBar';
import Providers from '@/providers';
import { ServerThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ServerThemeProvider attribute='class'>
      <html lang='en' className='h-svh transition-colors duration-75'>
        <body
          className={`${inter.className} relative flex h-full flex-col bg-neutral-50 text-neutral-800 transition-colors duration-75 dark:bg-neutral-800 dark:text-neutral-50`}
        >
          <Providers>
            <Nav />
            <main className='mx-auto h-full max-w-screen-2xl'>{children}</main>
          </Providers>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
